---
# Default values for kube-proximage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Proxy Configuration
config:
  ignoreList:
  - "123456789012.dkr.ecr.us-east-1.amazonaws.com"
  domainMap:
    docker.io: org-name-docker-io.jfrog.io
    quay.io: org-name-quay-io.jfrog.io
    gcr.io: org-name-gcr-io.jfrog.io
    k8s.gcr.io: org-name-k8s-gcr-io.jfrog.io
    us.gcr.io: org-name
    docker.elastic.co: org-name-docker-elastic-co.jfrog.io

image:
  # -- The docker image repository to use
  repository: jatalocks333/docker-proxy
  # -- The docker image tag to use
  tag: latest
  # -- The docker image pull policy
  pullPolicy: Always

# -- Enabled ServiceMonitor
ServiceMonitor:
  enabled: false