apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-proxy-webhook
  name: docker-proxy-webhook
  namespace: docker-proxy
spec:
  ports:
    - name: https
      port: 443  # must use 443 with our setup: https://github.com/kubernetes/kubernetes/issues/94889
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
    - name: monitoring
      port: 8081
      protocol: TCP
      targetPort: monitoring
  selector:
    app: docker-proxy-webhook
  type: ClusterIP